name: 🚪 Windows Builds

on:
  push:
    branches:
      - master
      - github_actions
      - godot3.x
  pull_request:
    branches:
      - master
  workflow_dispatch:

# Global Cache Settings
env:
  GODOT_BASE_BRANCH: "3.x"
  SCONS_CACHE_MSVC_CONFIG: true
  SCONS_CACHE_LIMIT: 4096

jobs:
  windows-editor:
    runs-on: "windows-latest"
    name: Editor

    steps:
      # Скачиваем Godot напрямую через чистый Git во избежание ошибки 403
      - name: Clone Godot Engine
        run: git clone --branch 3.x --depth 1 https://github.com/godotengine/godot.git .

      # А вот наш модуль качаем как обычно через checkout (тут наш токен сработает на ура)
      - uses: actions/checkout@v4
        with:
          path: modules/voxel

      # Загрузка кэша SCons
      - name: Load .scons_cache directory
        id: windows-editor-cache
        uses: actions/cache@v4
        with:
          path: /.scons_cache/
          key: ${{ github.job }}-${{ env.GODOT_BASE_BRANCH }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.job }}-${{ env.GODOT_BASE_BRANCH }}-${{ github.ref }}-${{ github.sha }}
            ${{ github.job }}-${{ env.GODOT_BASE_BRANCH }}-${{ github.ref }}
            ${{ github.job }}-${{ env.GODOT_BASE_BRANCH }}

      # Установка Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'

      # Настройка зависимостей
      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons pywin32
          python --version
          scons --version

      # Компиляция редактора
      - name: Compilation
        env:
          SCONS_CACHE: /.scons_cache/
        run: |
          scons -j2 verbose=yes warnings=all werror=yes platform=windows tools=yes tests=no target=release_debug

      # Сохранение готового файла
      - uses: actions/upload-artifact@v4
        with:
          name: godot.windows.opt.tools.64.exe
          path: bin/godot.windows.opt.tools.64.exe

  windows-template:
    runs-on: "windows-latest"
    name: Release

    steps:
      # Скачиваем Godot напрямую через чистый Git во избежание ошибки 403
      - name: Clone Godot Engine
        run: git clone --branch 3.x --depth 1 https://github.com/godotengine/godot.git .

      # Скачиваем наш модуль вокселей
      - uses: actions/checkout@v4
        with:
          path: modules/voxel

      # Загрузка кэша SCons
      - name: Load .scons_cache directory
        id: windows-template-cache
        uses: actions/cache@v4
        with:
          path: /.scons_cache/
          key: ${{ github.job }}-${{ env.GODOT_BASE_BRANCH }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.job }}-${{ env.GODOT_BASE_BRANCH }}-${{ github.ref }}-${{ github.sha }}
            ${{ github.job }}-${{ env.GODOT_BASE_BRANCH }}-${{ github.ref }}
            ${{ github.job }}-${{ env.GODOT_BASE_BRANCH }}

      # Установка Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'

      # Настройка зависимостей
      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons pywin32
          python --version
          scons --version

      # Компиляция экспортного шаблона
      - name: Compilation
        env:
          SCONS_CACHE: /.scons_cache/
        run: |
          scons -j2 verbose=yes warnings=all werror=yes platform=windows tools=no tests=no target=release

      # Сохранение готового шаблона
      - uses: actions/upload-artifact@v4
        with:
          name: godot.windows.opt.64.exe
          path: bin/godot.windows.opt.64.exe
